name: transparent_pointer
description: Provides TransparentPointer to control hit testing
version: 0.1.0
homepage: https://github.com/spkersten/flutter_transparent_pointer

environment:
  sdk: ">=2.12.0 <=3.2.3"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
